import { resolve, join } from 'node:path';
const root = resolve('.'), entry = join(root, 'dist', 'modules', 'QAInteract', 'mcp.js'), data = resolve(root, '.local/agentdock');
const generic = source => ({ command: process.execPath, args: [entry], env: { AIL_SOURCE: source, AIL_CLIENT_ID: source.toLowerCase(), AIL_DATA_DIR: data } });
console.log('Claude Desktop MCP JSON:');
console.log(JSON.stringify({ mcpServers: { 'agent-interaction': generic('Claude') } }, null, 2));
console.log('\nClaude Code .mcp.json:');
console.log(JSON.stringify({ mcpServers: { 'agent-interaction': { ...generic('Claude Code'), timeout: 1860000 } } }, null, 2));
console.log('\nClaude Code host settings fragment (merge into settings, NOT the MCP server env):');
console.log(JSON.stringify({env:{CLAUDE_CODE_MCP_AUTO_BACKGROUND_MS:'0'}},null,2));
console.log('\nOpenCode opencode.json (merge with your existing config):');
console.log(JSON.stringify({ mcp: { 'agent-interaction': { type: 'local', command: [process.execPath, entry], enabled: true, environment: { AIL_SOURCE:'OpenCode', AIL_CLIENT_ID:'opencode', AIL_DATA_DIR:data } } } }, null, 2));
console.log('\nCodex config.toml:');
console.log(`[mcp_servers.agent_interaction]\ncommand = '${process.execPath}'\nargs = ['${entry}']\ntool_timeout_sec = 1860\n\n[mcp_servers.agent_interaction.env]\nAIL_SOURCE = 'Codex'\nAIL_CLIENT_ID = 'codex'\nAIL_DATA_DIR = '${data}'`);
